server:
  port: 20000

spring:
  application:
    name: eureka-server
  profiles:
    active: dev

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    # 将localhost指向本机（host文件）
    hostname: localhost

